application: sushain97
version: 34
runtime: java
threadsafe: false
sessions_enabled: true

handlers:
- url: /
  servlet: contestWebsite.MainPage
  
- url: /about
  servlet: contestWebsite.About
  
- url: /registration
  servlet: contestWebsite.Registration
 
- url: /login
  servlet: contestWebsite.Login
 
- url: /directions
  servlet: contestWebsite.Directions
  
- url: /signout
  servlet: contestWebsite.Logout

- url: /createAdmin
  login: admin
  servlet: contestWebsite.CreateAdmin

- url: /adminPanel
  servlet: contestWebsite.AdminPanel
  
- url: /data
  servlet: contestWebsite.Data
  
- url: /contactUs
  servlet: contestWebsite.ContactUs
  
- url: /viewScores
  servlet: contestWebsite.ViewScores

- url: /contestResults
  servlet: contestWebsite.PublicResults

- url: /editRegistration
  servlet: contestWebsite.EditRegistration

- url: /forgotPass
  servlet: contestWebsite.ForgotPassword

- url: /tabulate
  servlet: contestTabulation.Main
  
- url: /403
  servlet: errors.Prohibited_403

- url: /401
  servlet: errors.Unauthorized_401
  
static_files:
  - include: /favicon.ico
  - include: /css/**.css
  - include: /js/**.js
  - include: /img/**

web_xml: |
  <error-page>
    <error-code>403</error-code>
    <location>/403</location>
  </error-page>
  <error-page>
    <error-code>401</error-code>
    <location>/401</location>
  </error-page>