application: sushain97
version: 29
runtime: java
threadsafe: false

handlers:
- url: /
  servlet: contestWebsite.MainPage
  
- url: /about
  servlet: contestWebsite.About
  
- url: /registration
  servlet: contestWebsite.Registration
 
- url: /login
  servlet: contestWebsite.Login
 
- url: /directions
  servlet: contestWebsite.Directions
  
- url: /signout
  servlet: contestWebsite.Logout

- url: /createAdmin
  login: admin
  servlet: contestWebsite.CreateAdmin

- url: /adminPanel
  servlet: contestWebsite.AdminPanel
  
- url: /data
  servlet: contestWebsite.Data
  
- url: /contactUs
  servlet: contestWebsite.ContactUs
  
- url: /viewScores
  servlet: contestWebsite.ViewScores

- url: /contestResults
  servlet: contestWebsite.PublicResults

- url: /editRegistration
  servlet: contestWebsite.EditRegistration

- url: /forgotPass
  servlet: contestWebsite.ForgotPassword

- url: /tabulate
  servlet: contestTabulation.Main
  
static_files:
  - include: /favicon.ico
  - include: /css/**.css
  - include: /js/**.js
  - include: /static/*
  - include: /static/img/*
  - include: /img/*